### ISSUE TITLE
Implement Splash Screen

### ISSUE THREAD

**Issue by mukul-dev** [ContriHUB/Easy2Do#1]
## Overview:
We need to implement a splash screen for the app that appears when the app is launched and stays visible for a few seconds before navigating to the main activity.

## Requirements:
1. The splash screen should have a background color, text/icon (you may use some animated text/icon too).
2. The splash screen should last for 2 seconds.
3. After the splash screen duration ends, the app should automatically navigate to the **MainActivity**.         
4. Ensure that the splash screen doesn’t appear when the app is relaunched from the background.

## Resources:
- [Android Splash Screen Documentation](https://developer.android.com/training/monitoring-device-state/splash-screens)
- [Android Intent Documentation](https://developer.android.com/reference/android/content/Intent)

##Additional Notes:

- Ensure code is clean and follows Android best practices.
- Feel free to ask questions if you need further clarification or assistance.

**Comment by Matheus-Parreira** [comment]
I wish to be assigned for this issue.

**Comment by ANKIT3058** [comment]
Could you please assign it to me?
