### ISSUE TITLE
Timer is not for 2 mins!

### ISSUE THREAD

**Issue by mukul-dev** [ContriHUB/Easy2Do#2]
## Bug:
In the "2-Min Task Timer" feature the UI shows "02:00" timer but when you click start it only runs for 10 seconds.

## Requirement:
1. Implement it correctly so that upon clicking start the timer runs for 2 mins.
2. Additionally, you may add a 5 second timer to let user get ready and start his task and display a text suggesting him to get ready in 5 seconds to start. After this 5 second timer ends the 2 min timer should start within which user can do his tiny task quickly!

## Additional Notes:

- Ensure code is clean and follows Android best practices.
- Feel free to ask questions if you need further clarification or assistance.

**Comment by Ayushi5498** [comment]
Hey MUKUL, please assign me this issue

**Comment by mukul-dev** [comment]
> Hey MUKUL, please assign me this issue

Yeah sure!

**Comment by adityapratap2005** [comment]
@mukul dev
In my earlier pull request I already fixed this issue.
May I make the PR with the previous code.

**Comment by mukul-dev** [comment]
Yes, i think you should! From the Contrihub portal you should make a PR verification request in order to get Points for this issue!
